// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: proto/servicegrpcredis.proto

package servicegrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RedisServiceClient is the client API for RedisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedisServiceClient interface {
	Get(ctx context.Context, in *RequestGet, opts ...grpc.CallOption) (*ResponseGet, error)
	Set(ctx context.Context, in *RequestSet, opts ...grpc.CallOption) (*ResponseSet, error)
	Del(ctx context.Context, in *RequestDel, opts ...grpc.CallOption) (*ResponseDel, error)
	Expire(ctx context.Context, in *RequestExpire, opts ...grpc.CallOption) (*ResponseExpire, error)
	HGet(ctx context.Context, in *RequestHGet, opts ...grpc.CallOption) (*ResponseHGet, error)
	HSet(ctx context.Context, in *RequestHSet, opts ...grpc.CallOption) (*ResponseHSet, error)
	HDel(ctx context.Context, in *RequestHDel, opts ...grpc.CallOption) (*ResponseHDel, error)
	HealthRedis(ctx context.Context, in *RequestHealthRedis, opts ...grpc.CallOption) (*ResponseHealthRedis, error)
}

type redisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRedisServiceClient(cc grpc.ClientConnInterface) RedisServiceClient {
	return &redisServiceClient{cc}
}

func (c *redisServiceClient) Get(ctx context.Context, in *RequestGet, opts ...grpc.CallOption) (*ResponseGet, error) {
	out := new(ResponseGet)
	err := c.cc.Invoke(ctx, "/servicegrpc.RedisService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) Set(ctx context.Context, in *RequestSet, opts ...grpc.CallOption) (*ResponseSet, error) {
	out := new(ResponseSet)
	err := c.cc.Invoke(ctx, "/servicegrpc.RedisService/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) Del(ctx context.Context, in *RequestDel, opts ...grpc.CallOption) (*ResponseDel, error) {
	out := new(ResponseDel)
	err := c.cc.Invoke(ctx, "/servicegrpc.RedisService/Del", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) Expire(ctx context.Context, in *RequestExpire, opts ...grpc.CallOption) (*ResponseExpire, error) {
	out := new(ResponseExpire)
	err := c.cc.Invoke(ctx, "/servicegrpc.RedisService/Expire", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) HGet(ctx context.Context, in *RequestHGet, opts ...grpc.CallOption) (*ResponseHGet, error) {
	out := new(ResponseHGet)
	err := c.cc.Invoke(ctx, "/servicegrpc.RedisService/HGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) HSet(ctx context.Context, in *RequestHSet, opts ...grpc.CallOption) (*ResponseHSet, error) {
	out := new(ResponseHSet)
	err := c.cc.Invoke(ctx, "/servicegrpc.RedisService/HSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) HDel(ctx context.Context, in *RequestHDel, opts ...grpc.CallOption) (*ResponseHDel, error) {
	out := new(ResponseHDel)
	err := c.cc.Invoke(ctx, "/servicegrpc.RedisService/HDel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) HealthRedis(ctx context.Context, in *RequestHealthRedis, opts ...grpc.CallOption) (*ResponseHealthRedis, error) {
	out := new(ResponseHealthRedis)
	err := c.cc.Invoke(ctx, "/servicegrpc.RedisService/HealthRedis", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedisServiceServer is the server API for RedisService service.
// All implementations should embed UnimplementedRedisServiceServer
// for forward compatibility
type RedisServiceServer interface {
	Get(context.Context, *RequestGet) (*ResponseGet, error)
	Set(context.Context, *RequestSet) (*ResponseSet, error)
	Del(context.Context, *RequestDel) (*ResponseDel, error)
	Expire(context.Context, *RequestExpire) (*ResponseExpire, error)
	HGet(context.Context, *RequestHGet) (*ResponseHGet, error)
	HSet(context.Context, *RequestHSet) (*ResponseHSet, error)
	HDel(context.Context, *RequestHDel) (*ResponseHDel, error)
	HealthRedis(context.Context, *RequestHealthRedis) (*ResponseHealthRedis, error)
}

// UnimplementedRedisServiceServer should be embedded to have forward compatible implementations.
type UnimplementedRedisServiceServer struct {
}

func (UnimplementedRedisServiceServer) Get(context.Context, *RequestGet) (*ResponseGet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRedisServiceServer) Set(context.Context, *RequestSet) (*ResponseSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedRedisServiceServer) Del(context.Context, *RequestDel) (*ResponseDel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Del not implemented")
}
func (UnimplementedRedisServiceServer) Expire(context.Context, *RequestExpire) (*ResponseExpire, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Expire not implemented")
}
func (UnimplementedRedisServiceServer) HGet(context.Context, *RequestHGet) (*ResponseHGet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HGet not implemented")
}
func (UnimplementedRedisServiceServer) HSet(context.Context, *RequestHSet) (*ResponseHSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HSet not implemented")
}
func (UnimplementedRedisServiceServer) HDel(context.Context, *RequestHDel) (*ResponseHDel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HDel not implemented")
}
func (UnimplementedRedisServiceServer) HealthRedis(context.Context, *RequestHealthRedis) (*ResponseHealthRedis, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthRedis not implemented")
}

// UnsafeRedisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedisServiceServer will
// result in compilation errors.
type UnsafeRedisServiceServer interface {
	mustEmbedUnimplementedRedisServiceServer()
}

func RegisterRedisServiceServer(s grpc.ServiceRegistrar, srv RedisServiceServer) {
	s.RegisterService(&RedisService_ServiceDesc, srv)
}

func _RedisService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/servicegrpc.RedisService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).Get(ctx, req.(*RequestGet))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/servicegrpc.RedisService/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).Set(ctx, req.(*RequestSet))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_Del_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).Del(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/servicegrpc.RedisService/Del",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).Del(ctx, req.(*RequestDel))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_Expire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestExpire)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).Expire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/servicegrpc.RedisService/Expire",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).Expire(ctx, req.(*RequestExpire))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_HGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestHGet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).HGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/servicegrpc.RedisService/HGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).HGet(ctx, req.(*RequestHGet))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_HSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestHSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).HSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/servicegrpc.RedisService/HSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).HSet(ctx, req.(*RequestHSet))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_HDel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestHDel)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).HDel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/servicegrpc.RedisService/HDel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).HDel(ctx, req.(*RequestHDel))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_HealthRedis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestHealthRedis)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).HealthRedis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/servicegrpc.RedisService/HealthRedis",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).HealthRedis(ctx, req.(*RequestHealthRedis))
	}
	return interceptor(ctx, in, info, handler)
}

// RedisService_ServiceDesc is the grpc.ServiceDesc for RedisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "servicegrpc.RedisService",
	HandlerType: (*RedisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _RedisService_Get_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _RedisService_Set_Handler,
		},
		{
			MethodName: "Del",
			Handler:    _RedisService_Del_Handler,
		},
		{
			MethodName: "Expire",
			Handler:    _RedisService_Expire_Handler,
		},
		{
			MethodName: "HGet",
			Handler:    _RedisService_HGet_Handler,
		},
		{
			MethodName: "HSet",
			Handler:    _RedisService_HSet_Handler,
		},
		{
			MethodName: "HDel",
			Handler:    _RedisService_HDel_Handler,
		},
		{
			MethodName: "HealthRedis",
			Handler:    _RedisService_HealthRedis_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/servicegrpcredis.proto",
}
